name: "Maven"

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]



jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.7'
          distribution: 'temurin'
          cache: maven
      
      - name: "Build"
        run: mvn package
  
  update-dependency-graph:
    
    permissions:
      contents: write
    
    steps:
      
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: "Update dependency graph"
        uses: advanced-security/maven-dependency-submission-action@v3
